options(repos=structure(c(CRAN="http://cran.us.r-project.org")))
install.packages("devtools")
require(devtools)
install.packages("gplots")
install.packages("https://cran.r-project.org/src/contrib/Archive/GMD/GMD_0.3.3.tar.gz")
install.packages("ecodist")
install.packages("MASS")
install.packages("jsonlite")
devtools::install_version("tm", version = "0.6-1")
install.packages("proxy")
install.packages("SnowballC")
install.packages("rplos")
install.packages("parfossil")
install.packages("doParallel")
install.packages("rentrez")
install.packages("curl")
install.packages("tibble")
install.packages("data.table")
install.packages("stringi")
install.packages("stringdist")
devtools::install_version("xml2", version="1.2.0")
devtools::install_github("ropenscilabs/jaod")
devtools::install_github("ropenscilabs/rbace")
install.packages("readr")
install.packages("plyr")
install.packages('logging')
install.packages('vegan')
install.packages('textcat')
install.packages('onehot')
devtools::install_github("sckott/ropenaire")
install.packages("rAltmetric", repos="http://cran.us.r-project.org")
install.packages("readr", repos="http://cran.us.r-project.org")
install.packages("remotes", repos="http://cran.us.r-project.org")
remotes::install_github("ropensci/rcrossref@async")
