options(repos=structure(c(CRAN="http://cran.us.r-project.org")))
install.packages("devtools")
require(devtools)
install.packages("GMD")
install.packages("ecodist")
install.packages("MASS")
install.packages("jsonlite")
devtools::install_version("tm", version = "0.6-1")
install.packages("proxy")
install.packages("SnowballC")
install.packages("rplos")
install.packages("parfossil")
install.packages("doParallel")
install.packages("rentrez")
install.packages("curl")
install.packages("tibble")
install.packages("data.table")
install.packages("stringi")
install.packages("stringdist")
devtools::install_version("xml2", version="1.2.0")
devtools::install_github("ropenscilabs/jaod")
devtools::install_github("ropenscilabs/rbace")
install.packages("readr")
install.packages("plyr")
install.packages('logging')
install.packages('vegan')
install.packages('textcat')
install.packages('onehot')
